pipeline{
    agent any
    stages{
        stage('Init'){
            steps{
                echo "Initiating the build"
            }
        }
        stage('Build'){
            steps{
                echo 'Building the package'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploy the package'
            }
        }
    }
}