pipeline{
    agent any
    stages{
        stage('Build code'){
            steps{
                sh '/opt/maven/bin/mvn -f pom.xml clean package'
            }


    post{
        success{
            archiveArtifacts artifacts: '**/*.war'
        }
    }
        }
        stage('Deploy to Staging'){
            steps{
                build 'Deploy_Application_Staging'
            }
        }
        stage('Deploy to Production'){
            steps{
                timeout(time: 5, unit: 'DAYS'){
                    input 'Approve the deployment?'
                }
                build 'Deploy_Application_Prod'
            }
        }
}
}