pipeline{
    agent any
    stages{
        stage('Build code'){
            steps{
                sh 'mvn -f pom.xml clean package'
            }
        }
    }
    post{
        success{
            archiveArtifacts artifacts: '**/*.war'
        }
    }
}